=== GuillaumeVDu/MTUSpline/xmlInput/NMSmodel.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation xml:lang="en">
      Body schema for NeuroMuscoloSkeletal Model.
      Copyright 2010 (C) Monica Reggiani. All rights reserved.
    </xs:documentation>
  </xs:annotation>
  
  <xs:complexType name = "MuscleType">
    <xs:sequence>
      <xs:element name = "name" type="xs:string"/>	
      <xs:element name = "C1" type="xs:double"/>
      <xs:element name = "C2" type="xs:double"/>
      <xs:element name = "shapeFactor" type="xs:double"/>
      <xs:element name = "optimalFiberLength" type="xs:double"/>
      <xs:element name = "pennationAngle" type="xs:double"/>
      <xs:element name = "tendonSlackLength" type="xs:double"/>
      <xs:element name = "maxIsometricForce" type="xs:double"/>
      <xs:element name = "strengthCoefficient" type="xs:double"/>
      
    </xs:sequence>		
  </xs:complexType>
   
  <xs:complexType name = "MusclesType">
    <xs:sequence>
      <xs:element name = "muscle" type = "MuscleType" minOccurs= "1" maxOccurs = "unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name = "MuscleSequenceType">
      <xs:list itemType = "xs:string"/>
  </xs:simpleType>
  
  <xs:complexType name = "ChannelType">
  	<xs:sequence>
  	  <xs:element name = "name" type="xs:string"/>
  	  <xs:element name = "muscleSequence" type = "MuscleSequenceType"/>
     </xs:sequence>	
  </xs:complexType>
  
  <xs:complexType name = "ChannelsType">
    <xs:sequence>
        <xs:element name = "Channel" type = "ChannelType" minOccurs = "1" maxOccurs = "unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name = "DoFType">
    <xs:sequence>
      <xs:element name = "name" type="xs:string"/>	
      <xs:element name = "muscleSequence" type = "MuscleSequenceType"/>
    </xs:sequence>	
  </xs:complexType>   
        
  <xs:complexType name = "DoFsType">
    <xs:sequence>
        <xs:element name = "DoF" type = "DoFType" minOccurs = "1" maxOccurs = "unbounded"/>
    </xs:sequence>
  </xs:complexType>  
  
  <xs:simpleType name = "PointsSequenceType">
      <xs:list itemType = "xs:double"/>
  </xs:simpleType>
  
  <xs:complexType name = "CurveType">
    <xs:sequence>
      <xs:element name = "name" type="xs:string" />
      <xs:element name = "xPoints" type = "PointsSequenceType"/>
      <xs:element name = "yPoints" type = "PointsSequenceType"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name = "MuscleDefaultType">
    <xs:sequence>
      <xs:element name = "percentageChange" type="xs:double"/>
      <xs:element name = "damping" type="xs:double"/>
      <xs:element name = "Curve" type="CurveType" minOccurs = "0" maxOccurs = "3"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name = "NMSmodelType">
    <xs:sequence>
      <xs:element name = "muscleDefault" type= "MuscleDefaultType"/>
      <xs:element name = "muscles" type = "MusclesType" />
      <xs:element name = "DoFs" type = "DoFsType"></xs:element>
      <xs:element name = "Channels" type = "ChannelsType"></xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name = "subject" type="NMSmodelType"/>
  
</xs:schema>

=== GuillaumeVDu/MTUSpline/cfg/TestData/gait2392Left.xml
<subject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XSD/NMSmodel.xsd">
	<muscleDefault>
		<percentageChange>0.15</percentageChange>
		<damping>0.5</damping>
		<Curve>
			<name>activeForceLength</name>
			<xPoints>-5 0 0.401 0.402 0.4035 0.52725 0.62875 0.71875 0.86125 1.045 1.2175 1.43875 1.61875 1.62 1.621 2.2 5</xPoints>
			<yPoints>0 0 0 0 0 0.226667 0.636667 0.856667 0.95 0.993333 0.77 0.246667 0 0 0 0 0</yPoints>
		</Curve>
		<Curve>
			<name>passiveForceLength</name>
			<xPoints>-5 0.998 0.999 1 1.1 1.2 1.3 1.4 1.5 1.6 1.601 1.602 5</xPoints>
			<yPoints>0 0 0 0 0.035 0.12 0.26 0.55 1.17 2 2 2 2</yPoints>
		</Curve>
		<Curve>
			<name>forceVelocity</name>
			<xPoints>-10 -1 -0.6 -0.3 -0.1 0 0.1 0.3 0.6 0.8 10</xPoints>
			<yPoints>0 0 0.08 0.2 0.55 1 1.4 1.6 1.7 1.75 1.75</yPoints>
		</Curve>
	</muscleDefault>
	<muscles>
		<muscle>
      <name>semimem_l</name>
		<C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.299710447656132</optimalFiberLength>
      <pennationAngle>15.0000001261</pennationAngle>
      <tendonSlackLength>0.213774229991262</tendonSlackLength>
      <maxIsometricForce>1288</maxIsometricForce>
      <strengthCoefficient>0.665617207409902</strengthCoefficient>
    </muscle>
    <muscle>
      <name>semiten_l</name>
	<C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.299710447656132</optimalFiberLength>
      <pennationAngle>15.0000001261</pennationAngle>
      <tendonSlackLength>0.213774229991262</tendonSlackLength>
      <maxIsometricForce>1288</maxIsometricForce>
      <strengthCoefficient>0.665617207409902</strengthCoefficient>
    </muscle>
    <muscle>
      <name>bifemlh_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.102302423048625</optimalFiberLength>
      <pennationAngle>0</pennationAngle>
      <tendonSlackLength>0.289975183039488</tendonSlackLength>
      <maxIsometricForce>896</maxIsometricForce>
      <strengthCoefficient>0.500000031885027</strengthCoefficient>
    </muscle>
    <muscle>
      <name>bifemsh_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.178670547450923</optimalFiberLength>
      <pennationAngle>23.000000117</pennationAngle>
      <tendonSlackLength>0.0957252799249049</tendonSlackLength>
      <maxIsometricForce>804</maxIsometricForce>
      <strengthCoefficient>0.500000031885027</strengthCoefficient>
    </muscle>
<muscle>
      <name>rect_fem_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.112585959832255</optimalFiberLength>
      <pennationAngle>4.99999985105</pennationAngle>
      <tendonSlackLength>0.293831069823685</tendonSlackLength>
      <maxIsometricForce>1169</maxIsometricForce>
      <strengthCoefficient>0.562381995368591</strengthCoefficient>
    </muscle>
    <muscle>
      <name>vas_med_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.0835317541585063</optimalFiberLength>
      <pennationAngle>4.99999985105</pennationAngle>
      <tendonSlackLength>0.109920121908373</tendonSlackLength>
      <maxIsometricForce>1294</maxIsometricForce>
      <strengthCoefficient>0.500000177514197</strengthCoefficient>
    </muscle>
    <muscle>
      <name>vas_int_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.0858855591156409</optimalFiberLength>
      <pennationAngle>3.00000013981</pennationAngle>
      <tendonSlackLength>0.130611908564377</tendonSlackLength>
      <maxIsometricForce>1365</maxIsometricForce>
      <strengthCoefficient>0.500000177514197</strengthCoefficient>
    </muscle>
    <muscle>
      <name>vas_lat_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.220108511329537</optimalFiberLength>
      <pennationAngle>4.99999985105</pennationAngle>
      <tendonSlackLength>0.107419382229801</tendonSlackLength>
      <maxIsometricForce>1871</maxIsometricForce>
      <strengthCoefficient>0.500000177514197</strengthCoefficient>
    </muscle>
    <muscle>
      <name>med_gas_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.0755645455772008</optimalFiberLength>
      <pennationAngle>16.9999998373</pennationAngle>
      <tendonSlackLength>0.437761575991988</tendonSlackLength>
      <maxIsometricForce>1558</maxIsometricForce>
      <strengthCoefficient>1.17061363965984</strengthCoefficient>
    </muscle>
    <muscle>
      <name>lat_gas_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.0756117073269633</optimalFiberLength>
      <pennationAngle>7.99999999086</pennationAngle>
      <tendonSlackLength>0.387686451006459</tendonSlackLength>
      <maxIsometricForce>683</maxIsometricForce>
      <strengthCoefficient>1.17061363965984</strengthCoefficient>
    </muscle>
    <muscle>
      <name>soleus_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.0702084174848329</optimalFiberLength>
      <pennationAngle>24.9999998282</pennationAngle>
      <tendonSlackLength>0.274894130323984</tendonSlackLength>
      <maxIsometricForce>3549</maxIsometricForce>
      <strengthCoefficient>0.549981312866525</strengthCoefficient>
    </muscle>
<muscle>
      <name>tib_ant_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>-2.40240316117061</shapeFactor>
      <optimalFiberLength>0.107905832172884</optimalFiberLength>
      <pennationAngle>4.99999985105</pennationAngle>
      <tendonSlackLength>0.240434369769458</tendonSlackLength>
      <maxIsometricForce>905</maxIsometricForce>
      <strengthCoefficient>0.549981312866525</strengthCoefficient>
    </muscle>
    <muscle>
      <name>per_brev_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>0.1</shapeFactor>
      <optimalFiberLength>0.05</optimalFiberLength>
      <pennationAngle>4.99999985105</pennationAngle>
      <tendonSlackLength>0.161</tendonSlackLength>
      <maxIsometricForce>435</maxIsometricForce>
      <strengthCoefficient>1.80606400349114</strengthCoefficient>
    </muscle>
    <muscle>
      <name>per_long_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>0.1</shapeFactor>
      <optimalFiberLength>0.049</optimalFiberLength>
      <pennationAngle>10.0000002751</pennationAngle>
      <tendonSlackLength>0.345</tendonSlackLength>
      <maxIsometricForce>943</maxIsometricForce>
      <strengthCoefficient>1.80606400349114</strengthCoefficient>
    </muscle>
    <muscle>
      <name>per_tert_l</name>
      <C1>-0.5</C1>
      <C2>-0.5</C2>
      <shapeFactor>0.1</shapeFactor>
      <optimalFiberLength>0.079</optimalFiberLength>
      <pennationAngle>12.9999998419</pennationAngle>
      <tendonSlackLength>0.1</tendonSlackLength>
      <maxIsometricForce>180</maxIsometricForce>
      <strengthCoefficient>1.80606400349114</strengthCoefficient>
    </muscle>
	</muscles>
	<DoFs>
 <DoF>
      <name>hip_flexion_l</name>
      <muscleSequence>semimem_l semiten_l bifemlh_l rect_fem_l</muscleSequence>
    </DoF>
		<DoF>
      <name>knee_angle_l</name>
      <muscleSequence>bifemlh_l bifemsh_l rect_fem_l semimem_l semiten_l med_gas_l lat_gas_l vas_med_l vas_int_l vas_lat_l</muscleSequence>
		</DoF>
		<DoF>
			<name>ankle_angle_l</name>
			<muscleSequence>per_long_l per_brev_l per_tert_l lat_gas_l soleus_l tib_ant_l med_gas_l</muscleSequence>
		</DoF>
	</DoFs>
	<Channels>
		<Channel>
			<name>gaslat_l</name>
			<muscleSequence>lat_gas_l med_gas_l</muscleSequence>
		</Channel>
		<Channel>
			<name>soleus_l</name>
			<muscleSequence>soleus_l</muscleSequence>
		</Channel>
		<Channel>
			<name>tibant_l</name>
			<muscleSequence>tib_ant_l</muscleSequence>
		</Channel>
		<Channel>
			<name>bicfemlh_l</name>
			<muscleSequence>bifemlh_l bifemsh_l</muscleSequence>
		</Channel>
		<Channel>
			<name>recfem_l</name>
			<muscleSequence>rect_fem_l</muscleSequence>
		</Channel>
		<Channel>
			<name>semimem_l</name>
			<muscleSequence>semimem_l semiten_l</muscleSequence>
		</Channel>
		<Channel>
			<name>vaslat_l</name>
			<muscleSequence>vas_lat_l vas_int_l</muscleSequence>
		</Channel>
		<Channel>
			<name>vasmed_l</name>
			<muscleSequence>vas_med_l vas_int_l</muscleSequence>
		</Channel>
	</Channels>
<!--Numbers of Muscle: 92, Numbers of DOF: 3--></subject>
